### ISSUE TITLE
lab-p-ftp-01 container crashing

### ISSUE THREAD

**Issue by cloudripper** [dolevf/Black-Hat-Bash#29]
- Following Black Hat Bash instructions in Early Access edition, 3/15/24
- Lab from commit 3e4360d
- VM: Kali-2024.2 / Prebuilt VM (QEMU)

**Issue**: _vsftpd crashing in lab-p-ftp-01 container - this prevents following book instructions, since x.x.x.11 is unresponsive and therefore no ftp server functions within lab network._

After cloning repo and setting up lab with `make init` or with manual installation and `make deploy`, lab-p-ftp-01 status shows exit 1. Attempting to troubleshoot, logs indicate vsftpd is unable to load. 

```bash
$ docker logs <p-ftp-01 container id>
 * Stopping FTP server vsftpd
No /usr/sbin/vsftpd found running; none killed.
   ...done.
 * Starting FTP server vsftpd
 * vsftpd failed - probably invalid config. 
 * 
```

This issue did not change despite testing different vsftpd configs. However, the issue did not appear when the container executed vsftpd directly (`/usr/sbin/vsftpd /etc/vsftpd.conf`); it only occurred when executed via init.d (`service vsftpd start`). Execution of init script appears to result in a _file descriptor leak_.

This issue was resolved by adding ulimits parameters for file descriptor limits to docker-compose.yml:
```diff
  p-ftp-01:
    container_name: p-ftp-01
    hostname: p-ftp-01.acme-infinity-servers.com
    build: 
      context: machines/
      dockerfile: p-ftp-01/Dockerfile
    networks:
      public:
        ipv4_address: 172.16.10.11
+    ulimits:
+      nofile:
+        soft: 10000
+        hard: 10000
```

Not sure if there is a better suggested approach to resolving this matter. At any rate, with that modification everything appears operational at this time (up to the end of Ch 4).

**Comment by dolevf** [comment]
That's interesting. I'm not seeing the same behavior and I just deployed it from scratch. Both `service vsftpd start` and calling vsftpd directly work.

```
root@p-ftp-01:/# service vsftpd start
 * Starting FTP server vsftpd                                                                                                                                                                                                                                                                                          [ OK ] 
root@p-ftp-01:/# pidof vsftpd
223
```

Then in Kali:
```
ftp 172.16.10.11
Connected to 172.16.10.11.
220 (vsFTPd 3.0.5)
Name (172.16.10.11:kali):  
530 This FTP server is anonymous only.
```

Software versions:

- Kali: 2024.1
- Docker Compose version v2.27.1
- Docker client: 26.1.4 
- Docker engine: 26.1.4

**Comment by dolevf** [comment]
When you added the ulimits, the `service vsftpd start` command started working?

**Comment by dolevf** [comment]
I was able to reproduce this after upgrading to Kali `2024.2`. 

From an initial investigation, it seems to be a problem with `start-stop-daemon` when it attempts to send `vsftpd` to the background. 

When executed this way:

`start-stop-daemon --start -m --oknodo --pidfile /var/run/vsftpd/vsftpd.pid --exec /usr/sbin/vsftpd --background`

vsftpd was not able to start. However, when the `--background` flag is removed, vsftpd starts fine. For now, I changed it so that vsftpd starts without start-stop-daemon. I will continue to investigate why this occurs. In the meantime, can you pull the latest & check if this solves your issue?

**Comment by cloudripper** [comment]
Latest commit works as intended. Thanks for the quick fix and thanks for poking around on this. 

It caught my curiosity - so I found myself in a rabbithole. I was initially curious on the vsftpd side of things and found the debian package mentions as issue with the vsftpd init script's start-stop-daemon'd --background option:


From _vsftpd-3.0.01/debian/vsftpd.README.Debian_:
> The included init script uses start-stop-daemon's --background option to run vsftpd in the background.  If you have "background=yes" in your configuration, the wrong PID will be recorded in /var/run/vsftpd/vsftpd.pid, and the init script may fail to restart or stop vsftpd later.  Just remove "background=yes"  from vsftpd.conf.

There was also mention of running in a container:
> If vsftpd is used within a Linux Container (LXC) or with NIS logins, make sure you use:
>    isolate=NO
>    isolate_network=NO
> in /etc/vsftpd.conf.

Neither of these config modifications resolved the issue. I then ran strace on the start-stop-daemon command in the container as the process was grinding 99% CPU and found the file descriptor leak. Checking `ulimit -a`, I found the file descriptor limit in the container set to a value of `1073741816`. Setting the file descriptor limit to a reasonable value, eg. `ulimit -n 10000`  allowed the start-stop-daemon to run without issue. Checking on the VM side, I found Kali 2024.2 kernel parameter for fs.nr_open set to the same high value of `1073741816` - near theoretical 32bit max signed int. 

By comparison, Kali 2024.1 (using x86 QEMU prebuilt VM) has fs,nr_open kernel parameter set to `1048576`.

Side note: I had a similar file descriptor leak using rustscan in the labs. [See this discussion](https://github.com/RustScan/RustScan/wiki/Common-Problems-and-their-Solutions). Certain situations (piping rustscan -g .. output, for instance) would cause file descriptor leaks in the rustscan docker.  I added `--ulimit nofile=10000:10000` to the rustscan docker alias (and included setting batch size to nofile limit):

```alias rustscan="docker run --network=host -it --ulimit nofile=10000:10000 --rm --name rustscan rustscan/rustscan:2.1.1 -b 10000 "```

**Comment by dolevf** [comment]
Yes, I do remember checking the background=no explicitly because I noticed ps -C vsftpd in the init script could not find the PID, but it didn't resolve the issue.

I greatly appreciate you opening an issue and providing a workaround for the benefit of other readers. Thank you!
