### ISSUE TITLE
sudo fails on p-jumpbox-01 due to permissions issue

### ISSUE THREAD

**Issue by 7ffb** [dolevf/Black-Hat-Bash#36]
![sudont](https://github.com/user-attachments/assets/9383ca2e-2346-4f5e-a9e3-50b10c48ce45)

Issue persisted after running 'make rebuild' as well.

Fixed by adding

chmod 755 /etc/sudoers.d/backup-user-sudo-config
chmod 755 /etc/sudoers.d/jmartinez-user-sudo-config

to the Dockerfile for p-jumpbox-01

**Comment by dolevf** [comment]
What is the issue that you're seeing?

**Comment by dolevf** [comment]
I don't see that these files are world writable?
```
root@p-jumpbox-01:/# cd /etc/sudoers.d
root@p-jumpbox-01:/etc/sudoers.d# ls -l
total 12
-r--r----- 1 root root 1068 Jan 29  2024 README
-rw-rw-r-- 1 root root   67 Nov 26 21:21 backup-user-sudo-config
-rw-rw-r-- 1 root root   27 Nov 26 21:21 jmartinez-user-sudo-config
```

What permissions are set in your case?
